# ... (tus pasos anteriores de init y plan) ...

      - name: Terraform Apply
        id: apply
        # El -auto-approve es necesario para que no pida confirmación manual en la nube
        run: terraform apply -auto-approve

      - name: Mostrar URL del Balanceador
        run: |
          echo "---------------------------------------------"
          echo "ACCEDE A TU APLICACIÓN AQUÍ:"
          terraform output url_balanceador
          echo "---------------------------------------------"